project:
  type: website
  output-dir: docs

website:
  title: "Консольные программы"
  navbar:
    right:
      - about.qmd
      - VK.qmd
format:
  html:
    smaller: true
    # theme: cosmo
    css: styles.css



